routes/web.php
<?php

//User
Route::get('/','User\HomeController@index')->name('home');
Route::get('/menu','User\CategoryController@index')->name('menu');
Route::get('/contact','User\ContactController@index')->name('contact');
Route::post('/contact','User\ContactController@send')->name('contact.send');
Route::get('/menu-item','User\ProductController@index')->name('product');
Route::get('specials','User\SpecialController@index')->name('special');
Route::get('/wings','User\WingsController@index')->name('wings');

Route::get('/online-ordering', function(){
	return view('user.online-ordering');
})->name('online.order');

//Admin
Route::get('/admin/home','Admin\HomeController@index')->name('admin.home');
Route::resource('/admin/products','Admin\ProductController');
Route::resource('/admin/specials','Admin\SpecialController');
Route::get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/admin/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

app/Http/Controllers/Admin/SpecialController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Special;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SpecialController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $specials = Special::all();
        return view('admin.specials.index',compact('specials'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.specials.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $special = new Special();

        $special->name = $request->name;
        $special->description = $request->description;
        $special->price = $request->price;
        $special->price2 = $request->price2;

        $special->save();

        return redirect()->back()->with('alert_session','Special successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $special = Special::where('id',$id)->first();

        return view('admin.specials.edit',compact('special'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $special = Special::where('id',$id)->first();

        $special->name = $request->name;
        $special->description = $request->description;
        $special->price = $request->price;
        $special->price2 = $request->price2;

        $special->save();

        return redirect()->back()->with('alert_session','Special successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $special = Special::where('id',$id)->delete();

        return redirect()->back()->with('alert_session','Special successfully deleted!');
    }
}

app/Http/Controllers/User/SpecialController.php
<?php

namespace App\Http\Controllers\User;

use App\Model\Special;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SpecialController extends Controller
{
    public function index()
    {
        $specials = Special::all();

        return view('user.specials',compact('specials'));
    }
}

resources/views/admin/specials/edit.blade.php
@extends('admin.layouts.app')

@section('Special','active')
@section('body-part')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Edit Special
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- general form elements -->
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">Edit Special</h3>
                            <br>
                            <a href="{{ route('specials.index') }}"><button class="btn btn-success btn-flat">Back</button></a>
                            @if(session('alert_session'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('alert_session') }}
                                </div>
                            @endif
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{ route('specials.update',$special->id) }}">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" name="name" class="form-control" value="{{ $special->name }}" id="exampleInputEmail1" placeholder="Enter name" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Description</label>
                                    <textarea class="textarea" placeholder="Enter description" name="description"
                                              style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ $special->description }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Price One($)</label>
                                    <input type="number" step="any" name="price" class="form-control" value="{{ $special->price }}" id="exampleInputEmail1" placeholder="Enter price">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Price Two($)</label>
                                    <input type="number" step="any" name="price2" class="form-control" value="{{ $special->price2 }}" id="exampleInputEmail1" placeholder="Enter price">
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/admin/specials/index.blade.php
@extends('admin.layouts.app')

@section('Special','active')
@section('body-part')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Specials
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">All Specials</h3>
                            <br>
                            <a href="{{ route('specials.create') }}">
                                <button class="btn btn-success btn-flat">New</button>
                            </a>
                            <br>
                            @if(session('alert_session'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('alert_session') }}
                                </div>
                            @endif
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Price One</th>
                                    <th>Price Two</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($specials as $special)
                                    <tr>
                                        <td>{{ $special->id }}</td>
                                        <td>{{ $special->name }}</td>
                                        <td>{!!  htmlspecialchars_decode($special->description)  !!}</td>
                                        <td>{{ $special->price }}</td>
                                        <td>{{ $special->price2 }}</td>
                                        <td>
                                            <a href="{{ route('specials.edit',$special->id) }}"><button class="btn btn-warning btn-flat btn-block">Edit</button></a>
                                        </td>
                                        <td>
                                            <form id="delete-form-{{ $special->id }}" method="POST" action="{{ route('specials.destroy',$special->id) }}" style="display: none;">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                            <a href="" onclick="if(confirm('Do you really want to delete this special?')){
                                                    event.preventDefault();
                                                    document.getElementById('delete-form-{{ $special->id }}').submit();
                                                    }else{
                                                    event.preventDefault();
                                                    }">
                                                <button class="btn btn-danger btn-flat btn-block">Delete</button>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Price One</th>
                                    <th>Price Two</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/specials/new.blade.php
@extends('admin.layouts.app')

@section('Special','active')
@section('body-part')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Create Special
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- general form elements -->
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">New Special</h3>
                            <br>
                            <a href="{{ route('specials.index') }}"><button class="btn btn-success btn-flat">Back</button></a>
                            @if(session('alert_session'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('alert_session') }}
                                </div>
                            @endif
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{ route('specials.store') }}">
                            @csrf
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Enter name" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Description</label>
                                    <textarea class="textarea" placeholder="Enter description" name="description"
                                              style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Price One($)</label>
                                    <input type="number" step="any" name="price" class="form-control" id="exampleInputEmail1" placeholder="Enter price">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Price Two($)</label>
                                    <input type="number" step="any" name="price2" class="form-control" id="exampleInputEmail1" placeholder="Enter price">
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

@endsection