routes/web.php
<?php

//User
Route::get('/','User\HomeController@index')->name('home');
Route::get('/menu','User\CategoryController@index')->name('menu');
Route::get('/contact','User\ContactController@index')->name('contact');
Route::post('/contact','User\ContactController@send')->name('contact.send');
Route::get('/menu-item','User\ProductController@index')->name('product');
Route::get('specials','User\SpecialController@index')->name('special');
Route::get('/wings','User\WingsController@index')->name('wings');

Route::get('/online-ordering', function(){
	return view('user.online-ordering');
})->name('online.order');

//Admin
Route::get('/admin/home','Admin\HomeController@index')->name('admin.home');
Route::resource('/admin/products','Admin\ProductController');
Route::resource('/admin/specials','Admin\SpecialController');
Route::get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/admin/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Category;
use App\Model\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->category) {
            $products = Product::with('category')->whereHas('category', function ($query) {
                $query->where('slug', request()->category);
            })->get();
            $category = Category::where('slug', request()->category)->first();
        }
        return view('admin.products.index',compact('products','category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::where('slug', request()->category)->first();
        return view('admin.products.new',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product();

        $product->name = $request->name;
        $product->category_id = $request->category_id;
        $product->description = $request->description;
        $product->small = $request->small;
        $product->medium = $request->medium;
        $product->large = $request->large;
        $product->extra_large = $request->extra_large;
        $product->price = $request->price;
        $product->platter = $request->platter;
        $product->extra_sauce = $request->extra_sauce;
        if ($request->new) {
            $product->new = 1;
        } else {
            $product->new = 0;
        }

        $product->save();

        return redirect()->back()->with('alert_session','Product successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::where('id',$id)->first();

        return view('admin.products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::where('id',$id)->first();

        $product->name = $request->name;
        $product->category_id = $request->category_id;
        $product->description = $request->description;
        $product->small = $request->small;
        $product->medium = $request->medium;
        $product->large = $request->large;
        $product->extra_large = $request->extra_large;
        $product->price = $request->price;
        $product->platter = $request->platter;
        $product->extra_sauce = $request->extra_sauce;
        if ($request->new) {
            $product->new = 1;
        } else {
            $product->new = 0;
        }

        $product->save();

        return redirect()->back()->with('alert_session','Product successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::where('id',$id)->delete();

        return redirect()->back()->with('alert_session','Product successfully deleted!');
    }
}

app/Http/Controllers/User/ProductController.php
<?php

namespace App\Http\Controllers\User;

use App\Model\Category;
use App\Model\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function index()
    {
        if (request()->category) {
            $products = Product::with('category')->whereHas('category', function ($query) {
                $query->where('slug', request()->category);
            })->get();
            $category = Category::where('slug', request()->category)->first();
        }

        return view('user.menu-items',compact('products','category'));
    }
}

resources/views/admin/products/edit.blade.php
@extends('admin.layouts.app')

@section('Product','active')
@section($product->category->slug,'active')
@section('body-part')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {{ $product->category->name }} Category
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- general form elements -->
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">Edit Product</h3>
                            <br>
                            <a href="{{ route('products.index', ['category='.$product->category->slug]) }}"><button class="btn btn-success btn-flat">Back</button></a>
                            @if(session('alert_session'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('alert_session') }}
                                </div>
                            @endif
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{ route('products.update',$product->id) }}">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="form-group">
                                    <input type="hidden" value="{{ $product->category->id }}" name="category_id">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputEmail1" value="{{ $product->name }}" placeholder="Enter name" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Description</label>
                                    <textarea class="textarea" placeholder="Enter description" name="description"
                                              style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ $product->description }}</textarea>
                                </div>
                                @if($product->category->slug != 'burgers' and $product->category->slug != 'panzzaroti' and $product->category->slug != 'chicken' and $product->category->slug != 'seafood')
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Small Price($)</label>
                                    <input type="number" step="any" name="small" class="form-control" id="exampleInputEmail1" value="{{ $product->small }}" placeholder="Enter small price">
                                </div>
                                @endif
                                @if($product->category->slug != 'seafood' and $product->category->slug != 'donairs' and $product->category->slug != 'panzzaroti' and $product->category->slug != 'poutine' and $product->category->slug != 'chicken' and $product->category->slug != 'subs_sandwiches' and $product->category->slug != 'appetizers' and $product->category->slug != 'burgers')
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Medium Price($)</label>
                                    <input type="number" step="any" name="medium" class="form-control" id="exampleInputEmail1" value="{{ $product->medium }}" placeholder="Enter medium price">
                                </div>
                                @endif
                                @if($product->category->slug != 'burgers' and $product->category->slug != 'panzzaroti' and $product->category->slug != 'chicken' and $product->category->slug != 'seafood')
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Large Price($)</label>
                                    <input type="number" step="any" name="large" class="form-control" id="exampleInputEmail1" value="{{ $product->large }}" placeholder="Enter large price">
                                </div>
                                @endif
                                @if($product->category->slug != 'seafood' and $product->category->slug != 'donairs' and $product->category->slug != 'panzzaroti' and $product->category->slug != 'poutine' and $product->category->slug != 'chicken' and $product->category->slug != 'subs_sandwiches' and $product->category->slug != 'appetizers' and $product->category->slug != 'burgers')
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Extra Large Price($)</label>
                                    <input type="number" step="any" name="extra_large" class="form-control" id="exampleInputEmail1" value="{{ $product->extra_large }}" placeholder="Enter extra large price">
                                </div>
                                @endif
                                @if($product->category->slug != 'pizza' and $product->category->slug != 'poutine')
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Price($)</label>
                                        <input type="number" step="any" name="price" class="form-control" id="exampleInputEmail1" value="{{ $product->price }}" placeholder="Enter price">
                                    </div>
                                @endif
                                @if($product->category->slug != 'pizza' and $product->category->slug != 'donairs' and $product->category->slug != 'panzzaroti' and $product->category->slug != 'poutine' and $product->category->slug != 'chicken' and $product->category->slug != 'subs_sandwiches' and $product->category->slug != 'appetizers' and $product->category->slug != 'seafood')
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Platter($)</label>
                                        <input type="number" step="any" name="platter" class="form-control" id="exampleInputEmail1" value="{{ $product->platter }}" placeholder="Enter price">
                                    </div>
                                @endif
                                @if($product->category->slug == 'donairs')
                                <div class="form-group">
                                        <label for="exampleInputEmail1">Extra Cheese or Meat($)</label>
                                        <input type="number" step="any" name="extra_sauce" class="form-control" id="exampleInputEmail1" value="{{ $product->extra_sauce }}" placeholder="Enter price">
                                    </div>
                                @endif
                                <div class="form-group">
                                    <label>New Product?</label>
                                    <br>
                                    <input type="checkbox" name="new" @if($product->new == 1) checked @endif>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/admin/products/index.blade.php
@extends('admin.layouts.app')

@section('Product','active')
@section($category->slug,'active')
@section('body-part')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {{ $category->name }} Category
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">All Products</h3>
                                <br>
                                <a href="{{ route('products.create', ['category='.$category->slug]) }}">
                                    <button class="btn btn-success btn-flat">New</button>
                                </a>
                                <br>
                                @if(session('alert_session'))
                                    <div class="alert alert-success" role="alert">
                                        {{ session('alert_session') }}
                                    </div>
                                @endif
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        @if($category->slug != 'burgers' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'chicken' and $category->slug != 'seafood')
                                            <th>Small($)</th>
                                        @endif
                                        @if($category->slug != 'seafood' and $category->slug != 'donairs' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'poutine' and $category->slug != 'chicken' and $category->slug != 'subs_sandwiches' and $category->slug != 'appetizers' and $category->slug != 'burgers')
                                            <th>Medium($)</th>
                                        @endif
                                        @if($category->slug != 'burgers' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'chicken' and $category->slug != 'seafood')
                                            <th>Large($)</th>
                                        @endif
                                        @if($category->slug != 'seafood' and $category->slug != 'donairs' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'poutine' and $category->slug != 'chicken' and $category->slug != 'subs_sandwiches' and $category->slug != 'burgers' and $category->slug != 'appetizers')
                                            <th>Extra Large($)</th>
                                        @endif
                                        @if($category->slug != 'pizza' and $category->slug != 'poutine')
                                            <th>Price($)</th>
                                        @endif
                                        @if($category->slug != 'pizza' and $category->slug != 'donairs' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'poutine' and $category->slug != 'chicken' and $category->slug != 'subs_sandwiches' and $category->slug != 'appetizers' and $category->slug != 'seafood')
                                            <th>Platter($)</th>
                                        @endif
                                        @if($category->slug == 'donairs')
                                            <th>Extra Cheese or Meat($)</th>
                                        @endif
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($products as $product)
                                        <tr>
                                            <td>{{ $product->id }}</td>
                                            <td>{{ $product->name }}</td>
                                            <td>{{ $product->description }}</td>
                                            @if($category->slug != 'burgers' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'chicken' and $category->slug != 'seafood')
                                                <td>{{ number_format($product->small,2) }}</td>
                                            @endif
                                            @if($category->slug != 'seafood' and $category->slug != 'donairs' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'poutine' and $category->slug != 'chicken' and $category->slug != 'subs_sandwiches' and $category->slug != 'burgers' and $category->slug != 'appetizers')
                                                <td>{{ number_format($product->medium,2) }}</td>
                                            @endif
                                            @if($category->slug != 'burgers' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'chicken' and $category->slug != 'seafood')
                                                <td>{{ number_format($product->large,2) }}</td>
                                            @endif
                                            @if($category->slug != 'seafood' and $category->slug != 'donairs' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'poutine' and $category->slug != 'chicken' and $category->slug != 'subs_sandwiches' and $category->slug != 'burgers' and $category->slug != 'appetizers')
                                                <td>{{ number_format($product->extra_large,2) }}</td>
                                            @endif
                                            @if($category->slug != 'pizza' and $category->slug != 'poutine')
                                                <td>{{ number_format($product->price,2) }}</td>
                                            @endif
                                            @if($category->slug != 'pizza' and $category->slug != 'donairs' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'poutine' and $category->slug != 'chicken' and $category->slug != 'subs_sandwiches' and $category->slug != 'appetizers' and $category->slug != 'seafood')
                                                <td>{{ number_format($product->platter,2) }}</td>
                                            @endif
                                            @if($category->slug == 'donairs')
                                                <th>{{ number_format($product->extra_sauce,2) }}</th>
                                            @endif
                                            <td>
                                                <a href="{{ route('products.edit',$product->id) }}">
                                                    <button class="btn btn-warning btn-flat btn-block">Edit</button>
                                                </a>
                                            </td>
                                            <td>
                                                <form id="delete-form-{{ $product->id }}" method="POST" action="{{ route('products.destroy',$product->id) }}" style="display: none;">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                                <a href="" onclick="if(confirm('Do you really want to delete this product?')){
                                                        event.preventDefault();
                                                        document.getElementById('delete-form-{{ $product->id }}').submit();
                                                        }else{
                                                        event.preventDefault();
                                                        }">
                                                    <button class="btn btn-danger btn-flat btn-block">Delete</button>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        @if($category->slug != 'burgers' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'chicken' and $category->slug != 'seafood')
                                            <th>Small($)</th>
                                        @endif
                                        @if($category->slug != 'seafood' and $category->slug != 'donairs' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'poutine' and $category->slug != 'chicken' and $category->slug != 'subs_sandwiches' and $category->slug != 'appetizers' and $category->slug != 'burgers')
                                            <th>Medium($)</th>
                                        @endif
                                        @if($category->slug != 'burgers' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'chicken' and $category->slug != 'seafood')
                                            <th>Large($)</th>
                                        @endif
                                        @if($category->slug != 'seafood' and $category->slug != 'donairs' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'poutine' and $category->slug != 'chicken' and $category->slug != 'subs_sandwiches' and $category->slug != 'burgers' and $category->slug != 'appetizers')
                                            <th>Extra Large($)</th>
                                        @endif
                                        @if($category->slug != 'pizza' and $category->slug != 'poutine' and $category->slug != 'appetizers')
                                            <th>Price($)</th>
                                        @endif
                                        @if($category->slug != 'pizza' and $category->slug != 'donairs' and $category->slug != 'panzzaroti' and $category->slug != 'garlic_fingers' and $category->slug != 'poutine' and $category->slug != 'chicken' and $category->slug != 'subs_sandwiches' and $category->slug != 'appetizers' and $category->slug != 'seafood')
                                            <th>Platter($)</th>
                                        @endif
                                        @if($category->slug == 'donairs')
                                            <th>Extra Cheese or Meat($)</th>
                                        @endif
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                </div>
        </section>
    </div>
@endsection